

name: Practise_workflow
on:
    push:
      branches: [ "master" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
       - run: date 
  windows:
    runs-on: windows-latest
    steps: 
        - name: step one
          uses: actions/checkout@v2
        - name: step two
          run: date
          
  macos:
    name: macos_method
    runs-on: macos-latest
    steps:
        - name: step one
          uses: actions/checkout@v2
        - name: step two
          run: Get-Date
          
  depends:
    name: fourth job
    runs-on: ubuntu-latest
    needs: [ubuntu,windows,macos]
    steps:
    - run: date
    
   
